# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---

Organizations:

    - &OrdererOrg
        Name: OrdererOrg

        ID: OrdererMSP

        MSPDir: crypto-config/ordererOrganizations/pretzel.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &Org1
        Name: Org1MSP

        ID: Org1MSP

        MSPDir: crypto-config/peerOrganizations/org1.pretzel.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org1MSP.admin')"

        AnchorPeers:
            - Host: peer0.org1.pretzel.com
              Port: 7051

    - &Org2
        Name: Org2MSP

        ID: Org2MSP

        MSPDir: crypto-config/peerOrganizations/org2.pretzel.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.peer', 'Org2MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org2MSP.admin', 'Org2MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org2MSP.admin')"

        AnchorPeers:
            - Host: peer0.org2.pretzel.com
              Port: 8051

    - &Org3
        Name: Org3MSP

        ID: Org3MSP

        MSPDir: crypto-config/peerOrganizations/org3.pretzel.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Org3MSP.admin', 'Org3MSP.peer', 'Org3MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('Org3MSP.admin', 'Org3MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('Org3MSP.admin')"

        AnchorPeers:
            - Host: peer0.org3.pretzel.com
              Port: 9051

Capabilities:
    Channel: &ChannelCapabilities
        V1_3: true
    Orderer: &OrdererCapabilities
        V1_1: true
    Application: &ApplicationCapabilities
        V1_3: true
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults

    OrdererType: solo

    Addresses:
        - orderer.pretzel.com:7050

    BatchTimeout: 2s

    BatchSize:

        MaxMessageCount: 10

        AbsoluteMaxBytes: 99 MB

        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    # EtcdRaft:
    #     Consenters:
    #         - Host: orderer.pretzel.com
    #           Port: 7050
    #           ClientTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer.pretzel.com/tls/server.crt
    #           ServerTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer.pretzel.com/tls/server.crt
    #         - Host: orderer2.pretzel.com
    #           Port: 7050
    #           ClientTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer2.pretzel.com/tls/server.crt
    #           ServerTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer2.pretzel.com/tls/server.crt
    #         - Host: orderer3.pretzel.com
    #           Port: 7050
    #           ClientTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer3.pretzel.com/tls/server.crt
    #           ServerTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer3.pretzel.com/tls/server.crt
    #         - Host: orderer4.pretzel.com
    #           Port: 7050
    #           ClientTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer4.pretzel.com/tls/server.crt
    #           ServerTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer4.pretzel.com/tls/server.crt
    #         - Host: orderer5.pretzel.com
    #           Port: 7050
    #           ClientTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer5.pretzel.com/tls/server.crt
    #           ServerTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer5.pretzel.com/tls/server.crt

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    ThreeOrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            pretzelConsortium:
                Organizations:
                    - *Org1
                    - *Org2
                    - *Org3
    ThreeOrgsChannel:
        Consortium: pretzelConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
                - *Org3
            Capabilities:
                <<: *ApplicationCapabilities

    # SampleDevModeKafka:
    #     <<: *ChannelDefaults
    #     Capabilities:
    #         <<: *ChannelCapabilities
    #     Orderer:
    #         <<: *OrdererDefaults
    #         OrdererType: kafka
    #         Kafka:
    #             Brokers:
    #             - kafka.pretzel.com:9092

    #         Organizations:
    #         - *OrdererOrg
    #         Capabilities:
    #             <<: *OrdererCapabilities
    #     Application:
    #         <<: *ApplicationDefaults
    #         Organizations:
    #         - <<: *OrdererOrg
    #     Consortiums:
    #         pretzelConsortium:
    #             Organizations:
    #             - *Org1
    #             - *Org2

    # SampleMultiNodeEtcdRaft:
    #     <<: *ChannelDefaults
    #     Capabilities:
    #         <<: *ChannelCapabilities
    #     Orderer:
    #         <<: *OrdererDefaults
    #         OrdererType: etcdraft
    #         EtcdRaft:
    #             Consenters:
    #             - Host: orderer.pretzel.com
    #               Port: 7050
    #               ClientTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer.pretzel.com/tls/server.crt
    #               ServerTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer.pretzel.com/tls/server.crt
    #             - Host: orderer2.pretzel.com
    #               Port: 7050
    #               ClientTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer2.pretzel.com/tls/server.crt
    #               ServerTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer2.pretzel.com/tls/server.crt
    #             - Host: orderer3.pretzel.com
    #               Port: 7050
    #               ClientTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer3.pretzel.com/tls/server.crt
    #               ServerTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer3.pretzel.com/tls/server.crt
    #             - Host: orderer4.pretzel.com
    #               Port: 7050
    #               ClientTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer4.pretzel.com/tls/server.crt
    #               ServerTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer4.pretzel.com/tls/server.crt
    #             - Host: orderer5.pretzel.com
    #               Port: 7050
    #               ClientTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer5.pretzel.com/tls/server.crt
    #               ServerTLSCert: crypto-config/ordererOrganizations/pretzel.com/orderers/orderer5.pretzel.com/tls/server.crt
    #         Addresses:
    #             - orderer.pretzel.com:7050
    #             - orderer2.pretzel.com:7050
    #             - orderer3.pretzel.com:7050
    #             - orderer4.pretzel.com:7050
    #             - orderer5.pretzel.com:7050

    #         Organizations:
    #         - *OrdererOrg
    #         Capabilities:
    #             <<: *OrdererCapabilities
    #     Application:
    #         <<: *ApplicationDefaults
    #         Organizations:
    #         - <<: *OrdererOrg
    #     Consortiums:
    #         pretzelConsortium:
    #             Organizations:
    #             - *Org1
    #             - *Org2
