# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:

  - Name: Orderer
    Domain: pretzel.com
    Specs:
      - Hostname: orderer
      
PeerOrgs:

  - Name: Org1
    Domain: org1.pretzel.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.pretzel.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org3
    Domain: org3.pretzel.com
    Template:
      Count: 1
    Users:
      Count: 1
